from PIL import Image, ImageDraw, ImageFont

def generate_pnl_card(name, pnl, filename):
    """
    Generate a Crypto PnL card as a JPG image.
    :param name: Name of the person
    :param pnl: Profit or Loss value
    :param filename: Name of the output image file
    """
    # Image dimensions
    width, height = 800, 400

    # Create a blank white image
    image = Image.new("RGB", (width, height), "white")
    draw = ImageDraw.Draw(image)

    # Fonts (update paths if necessary)
    try:
        title_font = ImageFont.truetype("arial.ttf", 40)  # Title font
        text_font = ImageFont.truetype("arial.ttf", 24)  # Text font
    except:
        print("Default font used. Install 'arial.ttf' for better design.")
        title_font = text_font = None

    # Draw a border
    border_color = "darkblue"
    draw.rectangle([(10, 10), (width - 10, height - 10)], outline=border_color, width=5)

    # Add title
    draw.text((width // 2 - 150, 20), "Crypto PnL Card", fill="black", font=title_font or text_font)

    # Add user name
    draw.text((50, 120), f"Name: {name}", fill="black", font=text_font)

    # Add profit or loss
    pnl_label = "Profit" if pnl >= 0 else "Loss"
    pnl_color = "green" if pnl >= 0 else "red"
    draw.text((50, 180), f"{pnl_label}: ${abs(pnl):,.2f}", fill=pnl_color, font=text_font)

    # Add footer
    footer_text = "Generated by Crypto PnL Generator"
    draw.text((width // 2 - 200, height - 50), footer_text, fill="gray", font=text_font)

    # Save the image
    image.save(filename)
    print(f"Image generated: {filename}")

# Main program
if __name__ == "__main__":
    print("Welcome to the Crypto PnL Card Generator!")
    
    while True:
        # Get user inputs
        name = input("Enter the name: ").strip()
        try:
            pnl = float(input("Enter the profit/loss amount (e.g., 200.5 or -150.75): ").strip())
        except ValueError:
            print("Invalid amount! Please enter a valid number.")
            continue
        
        # Generate the image
        filename = f"{name.replace(' ', '_')}_pnl_card.jpg"
        generate_pnl_card(name, pnl, filename)
        
        # Ask if the user wants to create another card
        another = input("Do you want to generate another card? (yes/no): ").strip().lower()
        if another != "yes":
            print("Goodbye!")
            break
