from reportlab.lib.pagesizes import letter
from reportlab.pdfgen import canvas
from reportlab.lib import colors

def generate_pnl_card(name, pnl, filename):
    """
    Generate a PnL card as a PDF.
    :param name: Name of the person
    :param pnl: Profit or Loss value
    :param filename: Name of the PDF file
    """
    # Create a canvas for the PDF
    pdf = canvas.Canvas(filename, pagesize=letter)
    pdf.setTitle("Crypto PnL Card")
    
    # Draw a border for the card
    pdf.setStrokeColor(colors.darkblue)
    pdf.setLineWidth(2)
    pdf.rect(50, 500, 500, 200, stroke=True, fill=False)
    
    # Add a title
    pdf.setFont("Helvetica-Bold", 20)
    pdf.drawString(150, 680, "Crypto PnL Report")
    
    # Add the name
    pdf.setFont("Helvetica", 16)
    pdf.drawString(70, 620, f"Name: {name}")
    
    # Add the profit or loss
    pdf.setFont("Helvetica", 16)
    pnl_label = "Profit" if pnl >= 0 else "Loss"
    pdf.setFillColor(colors.green if pnl >= 0 else colors.red)
    pdf.drawString(70, 580, f"{pnl_label}: ${abs(pnl):,.2f}")
    
    # Add a footer
    pdf.setFont("Helvetica-Oblique", 12)
    pdf.setFillColor(colors.black)
    pdf.drawString(70, 520, "Generated by Crypto PnL Generator")
    
    # Save the PDF
    pdf.save()
    print(f"PDF generated: {filename}")

# Main program
if __name__ == "__main__":
    print("Welcome to the Crypto PnL Card Generator!")
    
    while True:
        # Get user inputs
        name = input("Enter the name: ").strip()
        try:
            pnl = float(input("Enter the profit/loss amount (e.g., 200.5 or -150.75): ").strip())
        except ValueError:
            print("Invalid amount! Please enter a valid number.")
            continue
        
        # Generate the PDF
        filename = f"{name.replace(' ', '_')}_pnl_card.pdf"
        generate_pnl_card(name, pnl, filename)
        
        # Ask if the user wants to create another card
        another = input("Do you want to generate another card? (yes/no): ").strip().lower()
        if another != "yes":
            print("Goodbye!")
            break
